### ISSUE TITLE
Send every 0th ATX Noun to the ATX DAO Treasury

### ISSUE THREAD

**Issue by willyogo** [ATXDAO/nouns-monorepo#58]
<img width="685" alt="image" src="https://github.com/ATXDAO/nouns-monorepo/assets/26232238/31809b8d-c54d-4804-9d65-b89a819bd70b">

Currently every 0th ATX Noun (#0, #10, #20, etc) is sent to nounders.eth. As ATX DAO, we want every 0th ATX Noun to be sent to the ATX DAO Treasury so the community can do whatever the community wants with it (ie scholarships, competitions, even listing on a marketplace in theory)

AC:
1. Every 0th ATX Noun is sent to the ATX DAO Treasury (rather than current behavior of sending to nounders.eth, 0x2573C60a6D127755aA2DC85e342F7da2378a0Cc5)

**Comment by JacobHomanics** [comment]
Created PR, however we should leave this issue open until we can confirm that the changes work as intended!

**Comment by JacobHomanics** [comment]
@willyogo Ready to revisit this!

Basically already done, just need to configure deployment properly when the time comes. More in depth explanation can be found at [Issue 48](https://github.com/ATXDAO/nouns-monorepo/issues/48)

However, the UI needed a visual change to show "atxdao.eth" instead of "nounders.eth". Thus, the associated PR still needs to be accepted!

[PR](https://github.com/ATXDAO/nouns-monorepo/pull/59)

**Comment by willyogo** [comment]
awesome, thanks for the explanation @Hotmanics! checking this PR now https://github.com/ATXDAO/nouns-monorepo/pull/59 now
